### ISSUE TITLE
Improve demo for Maven Build Cache

### ISSUE THREAD

**Issue by mthmulders** [mthmulders/snail-pace-rocket-speed-demos#12]
Two things that we observed during the May 7 dray run:

* [x] Use `mvnd` for the first build that fills the cache
* [X] Automate the source code change

**Comment by bmarwell** [comment]
I opted in for mvnd3 all the time

**Comment by bmarwell** [comment]
mvnd3 runs into a weired problem with the cache (cannot find maven modules). and just replacing the last two commands with mvn will not work either, as mvnd cache != mvn cache.

So we stick with mvn

**Comment by bmarwell** [comment]
Same problem with mvn3, so reverting to mvnd3 and just leave out the third demo

**Comment by bmarwell** [comment]
Reverted back to mvnd, because I was missing the package phase
