### ISSUE TITLE
Detecting mvn3 / mvn4 aliases doesn't work

### ISSUE THREAD

**Issue by mthmulders** [mthmulders/snail-pace-rocket-speed-demos#6]
On my Macbook, the **setup.inc.sh** snippet doesn't properly detect the existing alias `mvn3`. As a result, it declares a function that invokes `mvn` (which in my case is `mvn4`).

In short, we need to re-think how to make the demo scripts portable.

On my machine:

* mvn = Maven 4
* mvn3 = Maven 3
* mvn4 = Maven 4

@bmarwell, which commands do you normally use?

**Comment by bmarwell** [comment]
I use, like most people, sdkman. And my default is still on mvn3.

We  probably could do a workaround for your local user... If $USER == mthmulders 😆

**Comment by mthmulders** [comment]
Could it have to do with the fact that I run zsh and not bash on my Macbook?

**Comment by mthmulders** [comment]
OK, I think I found a solution that works for Homebrew (which has two packages, *maven* and *maven-snapshot*). I think it could also work for SDKMan! - if you could let me know where it installs the Maven executable by default, then at least I can have it detect Maven 3.x, but I don't know if you have a default location for Maven snapshots...
